/**
 * "Chalk AI" — the built-in assistant bot (a regular `users` row with is_bot,
 * see migration 034) that answers questions about the app in a DM, or in a
 * group when mentioned as @chalk. Replies are generated by an OpenAI-compatible
 * /chat/completions endpoint (Groq by default — free tier, good Russian); the
 * key lives server-side only (config.ai), same policy as STT/Giphy.
 *
 * The whole feature is inert without GROQ_API_KEY: the bot user isn't created,
 * the chat-list entry stays hidden and /api/ai answers 503.
 */
import { v4 as uuid } from 'uuid';
import { randomBytes } from 'node:crypto';
import { config } from '../config/env';
import { supabaseAdmin } from './supabase';
import { checkMessage } from './autoModeration';
import { saveMessage, isConversationMember } from '../socket/messages';
import { getIO } from '../socket/registry';
import loggerBase from '../utils/logger';
const logger = loggerBase.child({ module: 'aiChalk' });

// Stable identity key: usernames are user-editable and display-oriented, the
// synthetic email is neither — it's how we find our own bot across restarts.
const CHALK_BOT_EMAIL = 'chalk-ai@bots.chalk.invalid';
const CHALK_BOT_USERNAME = 'Chalk';

// Everything the bot is allowed to claim about the app. Kept as a plain string
// (not a DB/RAG setup) on purpose: the feature set is small enough that the
// whole description fits in every request's system prompt.
const SYSTEM_PROMPT = `Ты — Chalk AI, дружелюбный встроенный помощник мессенджера Chalk. Отвечай на языке собеседника (по умолчанию — по-русски), коротко и по делу, без лишних формальностей. Если вопрос не про Chalk — можно просто поболтать, ты обычный приятный собеседник.

Что умеет Chalk (рассказывай только про это, не выдумывай функций):
• Личные чаты: текст, ответы (реплаи), реакции-эмодзи, редактирование и удаление сообщений, пересылка, закреплённые сообщения, GIF (кнопка GIF в чате), голосовые сообщения и видео-кружки, фото/видео/файлы. Опциональное сквозное шифрование — кнопка-замок в шапке личного чата.
• «Избранное» — чат с самим собой для заметок и пересланного (как в Telegram).
• Групповые чаты и общий (глобальный) чат всей платформы.
• Расшифровка чужих голосовых в текст — кнопка «В текст» на голосовом сообщении.
• Звонки: аудио и видео, прямо из чата. В звонке есть совместные развлечения: мини-игры и совместный просмотр.
• Серверы (как в Discord): текстовые и голосовые каналы, роли участников, права на каналы. Создаются во вкладке серверов.
• Поиск собеседников: свайпы анкет (дискавери) и мэтчи — совпало у обоих, получился чат.
• Друзья: заявки в друзья, список друзей, статусы онлайн.
• Истории (stories) — короткие публикации, исчезающие со временем.
• Мини-игры: шахматы, морской бой, 2048, гонки и другие — в разделе игр и в звонках.
• Боты: в настройках, раздел «Боты», можно создать своего бота и получить API-токен для отправки сообщений через HTTP API.
• Кастомизация: настройки → «Дизайн» — темы, цвета, фон чата (обои можно менять и в самом чате).
• Настройки приватности и безопасности: блокировка пользователей, вход по паролю или passkey.

Если тебя спрашивают, как что-то сделать — объясни по шагам, где это найти. Если не знаешь или функции нет — честно скажи, что такого пока нет. Не притворяйся человеком: ты бот, и это нормально.`;

// How much recent conversation rides along with each request. 20 short chat
// messages ≈ well under 2k tokens — cheap and plenty for context.
const HISTORY_LIMIT = 20;
const MAX_REPLY_TOKENS = 512;

export function isAiEnabled(): boolean {
  return config.ai.enabled;
}

// ── Bot identity ──────────────────────────────────────────────────────────
// Created lazily on first use (not at startup — keeps boot free of network
// calls and tests unaffected). Cached for the process lifetime.
let cachedBotId: string | null = null;
let ensuring: Promise<string | null> | null = null;

export async function ensureChalkBot(): Promise<string | null> {
  if (!config.ai.enabled) return null;
  if (cachedBotId) return cachedBotId;
  if (ensuring) return ensuring;
  ensuring = (async () => {
    try {
      const { data: existing } = await supabaseAdmin
        .from('users')
        .select('id')
        .eq('email', CHALK_BOT_EMAIL)
        .maybeSingle();
      if (existing) { cachedBotId = existing.id; return existing.id; }

      const botId = uuid();
      // Self-owned: users_bot_owner_consistency (migration 034) requires every
      // bot to have an owner, but a system bot has no human owner — pointing
      // the FK at itself satisfies the constraint without a schema change, and
      // it never shows up in anyone's /api/bots list (bots can't log in).
      // No bot_token_hash → the Bot-token HTTP API can't impersonate it.
      const { data: bot, error } = await supabaseAdmin
        .from('users')
        .insert({
          id: botId,
          username: CHALK_BOT_USERNAME,
          email: CHALK_BOT_EMAIL,
          password_hash: randomBytes(32).toString('hex'),
          is_bot: true,
          bot_owner_id: botId,
          avatar_emoji: '✨',
          onboarding_completed: true,
          status: 'online',
          created_at: new Date().toISOString(),
        })
        .select('id')
        .single();
      if (error) {
        // Unique username collision (someone registered "Chalk") — retry once
        // with a suffixed name rather than failing the feature forever.
        if (String(error.code) === '23505') {
          const { data: retry, error: err2 } = await supabaseAdmin
            .from('users')
            .insert({
              id: botId,
              username: `${CHALK_BOT_USERNAME} AI`,
              email: CHALK_BOT_EMAIL,
              password_hash: randomBytes(32).toString('hex'),
              is_bot: true,
              bot_owner_id: botId,
              avatar_emoji: '✨',
              onboarding_completed: true,
              status: 'online',
              created_at: new Date().toISOString(),
            })
            .select('id')
            .single();
          if (err2) { logger.error({ err: err2 }, 'Failed to create Chalk AI bot'); return null; }
          cachedBotId = retry.id; return retry.id;
        }
        logger.error({ err: error }, 'Failed to create Chalk AI bot');
        return null;
      }
      cachedBotId = bot.id;
      logger.info({ botId: bot.id }, 'Chalk AI bot created');
      return bot.id;
    } finally {
      ensuring = null;
    }
  })();
  return ensuring;
}

// ── LLM call ──────────────────────────────────────────────────────────────
type ChatTurn = { role: 'system' | 'user' | 'assistant'; content: string };

async function completeChat(messages: ChatTurn[]): Promise<string | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 30_000);
  try {
    const resp = await fetch(config.ai.apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${config.ai.apiKey}`,
      },
      body: JSON.stringify({
        model: config.ai.model,
        messages,
        max_tokens: MAX_REPLY_TOKENS,
        temperature: 0.7,
      }),
      signal: controller.signal,
    });
    if (!resp.ok) {
      const body = await resp.text().catch(() => '');
      logger.error({ status: resp.status, body: body.slice(0, 500) }, 'Groq chat completion failed');
      return null;
    }
    const data: any = await resp.json();
    const text = data?.choices?.[0]?.message?.content;
    return typeof text === 'string' && text.trim() ? text.trim() : null;
  } catch (e: any) {
    logger.error({ err: e }, 'Groq chat completion errored');
    return null;
  } finally {
    clearTimeout(timer);
  }
}

// ── Per-user personalization (migration 035) ──────────────────────────────
// The user's own instructions for the assistant («зови меня Саша», «отвечай
// покороче»). Read errors (e.g. migration not applied yet) degrade to null —
// the assistant just behaves stock.
export async function getUserAiInstructions(userId: string): Promise<string | null> {
  const { data, error } = await supabaseAdmin
    .from('users')
    .select('ai_instructions')
    .eq('id', userId)
    .maybeSingle();
  if (error) return null;
  const text = (data as any)?.ai_instructions;
  return typeof text === 'string' && text.trim() ? text.trim().slice(0, 1000) : null;
}

// The user's wishes are style/persona tuning, not an override channel — the
// base prompt (feature facts, honesty about being a bot) stays authoritative.
function withUserInstructions(base: string, instructions: string | null): string {
  if (!instructions) return base;
  return `${base}

Пользователь настроил тебя под себя. Выполняй эти пожелания, если они не противоречат правилам выше (не выдумывать функции, не притворяться человеком):
«${instructions}»`;
}

// ── History → prompt ──────────────────────────────────────────────────────
// Only plaintext 'text' messages carry over; media/voice/encrypted rows are
// skipped (the model can't see them anyway). Oldest-first for the API.
async function buildHistory(conversationId: string, botId: string): Promise<ChatTurn[]> {
  const { data } = await supabaseAdmin
    .from('messages')
    .select('sender_id, text, type, is_encrypted, deleted_at, sender:users!messages_sender_id_fkey ( username )')
    .eq('conversation_id', conversationId)
    .order('created_at', { ascending: false })
    .limit(HISTORY_LIMIT);
  const rows = (data || []).filter((m: any) =>
    m.type === 'text' && !m.is_encrypted && !m.deleted_at && typeof m.text === 'string' && m.text.trim());
  return rows.reverse().map((m: any): ChatTurn => (
    m.sender_id === botId
      ? { role: 'assistant', content: m.text }
      : { role: 'user', content: `${(m.sender && m.sender.username) || 'Пользователь'}: ${m.text}` }
  ));
}

// ── Reply trigger ─────────────────────────────────────────────────────────
// Fire-and-forget from the chat:message socket handler (never blocks or fails
// the user's own send). Replies when the bot is a member of the conversation
// AND (it's a 1:1 DM with the bot, OR the message mentions @chalk in a group).
const inFlight = new Set<string>();

export function maybeAiReply(conversationId: string, senderId: string, text: string): void {
  if (!config.ai.enabled) return;
  void (async () => {
    try {
      const botId = await ensureChalkBot();
      if (!botId || senderId === botId) return;
      // One generation per conversation at a time — a burst of messages while
      // the model is thinking shouldn't queue up N replies (free-tier budget).
      if (inFlight.has(conversationId)) return;
      if (!(await isConversationMember(conversationId, botId))) return;

      const { data: conv } = await supabaseAdmin
        .from('conversations')
        .select('type')
        .eq('id', conversationId)
        .maybeSingle();
      if (!conv) return;
      // 1:1 with the bot ('ai' is the dedicated sidebar conversation, 'direct'
      // covers legacy chats created before the 'ai' type existed) → always
      // reply; groups need an explicit @chalk mention.
      if (conv.type !== 'direct' && conv.type !== 'ai' && !/@chalk\b/i.test(text)) return;

      inFlight.add(conversationId);
      try {
        const io = getIO();
        io?.to(`chat:${conversationId}`).emit('chat:typing', {
          conversationId, userId: botId, username: CHALK_BOT_USERNAME, kind: 'typing',
        });

        const history = await buildHistory(conversationId, botId);
        const instructions = await getUserAiInstructions(senderId);
        const reply = await completeChat([{ role: 'system', content: withUserInstructions(SYSTEM_PROMPT, instructions) }, ...history]);
        if (!reply) return;

        // Same plaintext moderation gate as every other bot message — the
        // model shouldn't produce anything that trips it, but if it does the
        // reply is dropped, not special-cased around the filter.
        const verdict = await checkMessage(botId, reply);
        if (!verdict.ok) { logger.warn({ conversationId }, 'Chalk AI reply rejected by moderation'); return; }

        const msg = await saveMessage({ conversationId, senderId: botId, text: reply, type: 'text' });
        getIO()?.to(`chat:${conversationId}`).emit('chat:message', msg as any);
      } finally {
        inFlight.delete(conversationId);
      }
    } catch (e: any) {
      logger.error({ err: e, conversationId }, 'Chalk AI reply failed');
    }
  })();
}

// ── Voice-call replies ────────────────────────────────────────────────────
// The "call" with the bot is browser-side: Web Speech API transcribes the
// user's speech, the text comes here (POST /api/ai/reply), and the reply is
// spoken back by speechSynthesis. Nothing is persisted — the transcript
// lives only in the client for the duration of the call, so the caller
// sends the running history with each request.
const VOICE_SYSTEM_PROMPT = `${SYSTEM_PROMPT}

Сейчас ты разговариваешь ГОЛОСОМ: твой ответ будет озвучен синтезом речи. Поэтому отвечай очень коротко — одно-три разговорных предложения. Никаких эмодзи, списков, markdown, форматирования и URL — только естественная устная речь.`;

export async function voiceReply(history: { role: 'user' | 'assistant'; content: string }[], userId?: string): Promise<string | null> {
  if (!config.ai.enabled) return null;
  const instructions = userId ? await getUserAiInstructions(userId) : null;
  return completeChat([{ role: 'system', content: withUserInstructions(VOICE_SYSTEM_PROMPT, instructions) }, ...history]);
}

// ── First-open greeting ───────────────────────────────────────────────────
// Called by POST /api/ai/chat right after creating the conversation, so the
// chat doesn't open onto an empty void — the bot introduces itself instead.
export async function sendGreeting(conversationId: string): Promise<void> {
  const botId = await ensureChalkBot();
  if (!botId) return;
  const text = 'Привет! Я Chalk AI — помощник этого мессенджера. Спрашивай про любые функции: чаты, звонки, серверы, игры, ботов, настройки. Или просто поболтаем 🙂';
  try {
    const msg = await saveMessage({ conversationId, senderId: botId, text, type: 'text' });
    getIO()?.to(`chat:${conversationId}`).emit('chat:message', msg as any);
  } catch (e: any) {
    logger.error({ err: e, conversationId }, 'Chalk AI greeting failed');
  }
}
